services:
  www:
    build: .
    image: www:health
    command: ["npm", "run", "dev"]
    ports:
      - 3000:80
    healthcheck:
      test: ["CMD", "curl -f http://localhost:3000 || exit 1"]
      timeout: 30s
      interval: 1m
      retries: 3
