services:
  api:
    build: ./api
    command: ["npm", "run", "dev"]
    ports:
      - "3001:3000"
    environment:
      PORT: 3000
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DATABASE: "postgres"
    volumes:
      - ./api:/app
      # Cela montera le répertoire node_modules sur la machine hôte.
      - /app/node_modules
    depends_on:
      db:
        condition: service_healthy
    networks:
      - net

  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    volumes:
      - ./db-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres" ]
      interval: "5s"
    ports:
      - "5432:5432"
    networks:
      - net

volumes:
  db-data:

networks:
  net:
